sudo: required
dist: trusty
addons:
  - firefox: "60.0"
      
language: node_js
node_js:
  - 10

before_install:
  - cd './user-application'

before_script:
  - npm install -g ionic cordova
  - npm install
  

script:
  - ng test  --browser=Firefox --watch=false 
