sudo: required
dist: xenial
addons:
  firefox: latest-esr

language: node_js
node_js:
  - "10"
  
language: python
python:
  - "3.7"  

cache:
  directories:
    - './user-application/node_modules'
    - './server/node_modules'

before_install:
  - cd './server'
  - pip install -r requirements.txt
  - cd '../user-application'

services:
  - xvfb

before_script:
# - sudo ln -s /var/lib/dbus/machine-id /etc/machine-id
  - npm install -g ionic cordova
  - npm install -g @angular/cli
  - npm install

script:
  - ng test --watch=false
  - cd '../server'
  - python3 tests.py
