sudo: false
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - 10

before_install:
  - cd './user-application'

before_script:
  - npm install
  - npm install -g ionic cordova

script:
  - ng test
