sudo: false

addons:
  chrome: stable
      
language: node_js
node_js:
  - 10

before_install:
  - cd './user-application'

before_script:
  - npm install
  - npm install -g ionic cordova

script:
  - ng test
